### ISSUE TITLE
Unexpected IO output with two openPMD multi plugin instances and seperate .toml configurations

### ISSUE THREAD

**Issue by pordyna** [ComputationalRadiationPhysics/picongpu#4590]
@franzpoeschel I'm running a simulation with the follwing IO configuration (as a follow-up to https://github.com/openPMD/openPMD-api/issues/1457):
` --openPMD.toml ../input/etc/picongpu/openPMD_simData.toml --openPMD.toml ../input/etc/picongpu/openPMD_simData_frequent.toml`

`etc/picongpu/openPMD_simData_frequent.toml`
```toml
# The following parameters need not be specified
# If a parameter is left unspecified, it falls back to its default value
file = "frequent"    # replaces --openPMD.file,
                   # given value is the default

infix = "%06T"         # replaces --openPMD.infix,
                   # default is "%06T"
ext = "bp5"         # replaces --openPMD.ext,
                   # given value is the default
backend_config = "@../input/etc/picongpu/adios_config.json"    # replaces --openPMD.json,
                                           # default is "{}"
data_preparation_strategy = "mappedMemory" # replaces --openPMD.dataPreparationStrategy,
                                           # default is "doubleBuffer"
range = "270:1170,270:1170,32:1108"

# Periods and data sources are specified independently per reading application
# The application names can be arbitrary and are not interpreted, except
# potentially for logging and other messages.
[sink.disk.period]
# Each entry here denotes a periodicity combined with data sources requested
# by the reading code from PIConGPU at the specified periodicity
"0:0,4356:9072:2" = ["e_all_density", "e_all_densityOverGammaSquared", "B"]
```
`etc/picongpu/opopenPMD_simData.toml `
```toml
# The following parameters need not be specified
# If a parameter is left unspecified, it falls back to its default value
file = "simData"    # replaces --openPMD.file,
                   # given value is the default

infix = "%06T"         # replaces --openPMD.infix,
                   # default is "%06T"
ext = "bp5"         # replaces --openPMD.ext,
                   # given value is the default
backend_config = "@../input/etc/picongpu/adios_config.json"    # replaces --openPMD.json,
                                           # default is "{}"
data_preparation_strategy = "mappedMemory" # replaces --openPMD.dataPreparationStrategy,
                                           # default is "doubleBuffer"


# Periods and data sources are specified independently per reading application
# The application names can be arbitrary and are not interpreted, except
# potentially for logging and other messages.
[sink.disk.period]
# Each entry here denotes a periodicity combined with data sources requested
# by the reading code from PIConGPU at the specified periodicity
"4356:4356,450" = "species_all"
"1:1,252" = "fields_all"
```
`/etc/picongpu/adios_config.json`
```json
{"adios2": {
    "engine": {
        "parameters": {
             "AggregatorRatio" : "1"
             ,"BufferChunkSize" : "2147381248"
        }
    }
}}

```
The result is rather weird. There are only `frequent...` directories and no `simData` at all. But there exists for example `frequent00450.bp5` so sth from the range of the `simData` configuration. Weirdly enough:

```bash
$ bpls frequent000450.bp5/
  uint64_t  /data/450/fields/picongpu_idProvider/nextId   {12, 6, 6}
  uint64_t  /data/450/fields/picongpu_idProvider/startId  {12, 6, 6}
```
So, there are neither the particle data expected for this time step nor the field data expected for the plugin instance with the `frequent` file name.

Frequent output looks alrigth to me:
```bash
$ bpls frequent004356.bp5/
  float     /data/4356/fields/B/x                            {1076, 900, 900}
  float     /data/4356/fields/B/y                            {1076, 900, 900}
  float     /data/4356/fields/B/z                            {1076, 900, 900}
  float     /data/4356/fields/e_all_density                  {1076, 900, 900}
  float     /data/4356/fields/e_all_densityOverGammaSquared  {1076, 900, 900}
  uint64_t  /data/4356/fields/picongpu_idProvider/nextId     {12, 6, 6}
  uint64_t  /data/4356/fields/picongpu_idProvider/startId    {12, 6, 6}
```

@franzpoeschel Could it be that `[sink.disk.period]` can't be the same in both files? Or is the toml configuration not working with the multiplugin feature?
